version: '3'

volumes:
  nextcloud-data:

networks:
  frontend:
    external:
      name: proxy
  db:
    external: true

services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      #- POSTGRES_PASSWORD=change_me_please
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=postgres
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    env_file: .env
    ports:
      - "8000:80"
    networks:
      - frontend
      - db

#  nextcloud-db:
#    image: postgres
#    restart: always
      #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
#    volumes:
#      - nextcloud-db:/var/lib/postgresql
#    environment:
      #- POSTGRES_PASSWORD=change_me_please
#      - POSTGRES_DB=nextcloud
#      - POSTGRES_USER=nextcloud
#    env_file: .env
#    networks:
#      - backend

