version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_POLL_INTERVAL=21600
      - WATCHTOWER_MONITOR_ONLY=true
    env_file: .env
    restart: always
